apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redis-enterprise-database
spec:
  memorySize: 4GB
  persistence: "snapshotEvery1Hour"
  replication: true
  rolesPermissions:
  - type: redis-enterprise
    role: "DB Member"
    acl: "Not Dangerous"
  modulesList: 
  - name: search
    version: 2.4.6
